rm -rf build 
rm -rf Core 
rm -rf LWIP 
rm -rf Middlewares 
rm -rf newlib_lock_glue.c 
rm -rf startup_stm32f767xx.s 
rm -rf stm32_lock.h 
rm -rf Drivers 
rm -rf Makefile 
rm -rf .mxproject 
rm -rf Scripts 
rm -rf STM32F767ZITx_FLASH.ld 
rm -rf USB_DEVICE
